#!/usr/bin/env python3
"""
Evolutionary Engine for A/B Testing and Hypothesis Validation

ARCHITECTURAL PURPOSE:
This is the "brain" of the meta-analyzer, or the "Trainer". Its job is to analyze the trading
results of the "Champion" and "Pretenders" to make the system better. It operates in two modes:

1.  HYPOTHESIS GENERATION: It analyzes the history of the "Champion's" errors (from the `ExperienceDiary`)
    and generates new "rules" (hypotheses for improvement) that could be tested.
    For example: "Avoid long positions when VIX > 30".

2.  PERFORMANCE EVALUATION: It periodically compares the financial results of the "Champion"
    and the "Pretenders" (which are testing new hypotheses). If a "Pretender" consistently
    shows better results, the "Trainer" signals this, proposing to
    "promote" its rules into the main strategy.

This module is an ORCHESTRATOR of the safe self-improvement process through A/B testing.
"""

import json
import sqlite3
from dataclasses import dataclass
from datetime import datetime
from typing import Any

import pandas as pd

from src.analytics.arena.arena_battle import get_trading_arena
from src.config.unified_config_manager import UnifiedConfigManager
from src.core.logging.logger import ProjectLogger
from src.data.management.data_manager import DataManager
from src.devtools.rule_generator import ContextRuleGenerator
from src.meta_learning.base import BaseMetaComponent
from src.meta_learning.memory.diary_engine import DiaryEngine


@dataclass
class TradingRule:
    """ Data contract for a single trading rule generated by the Trainer """
    rule_id: str
    description: str
    conditions: dict[str, Any]
    action: str
    status: str = "experimental"

class LearningLoopsEngine(BaseMetaComponent):
    """
    The main class that implements the "Trainer" logic, integrating DataManager,
    RuleGenerator, and Arena for self-improving trading logic.
    """

    def __init__(self, config_manager: UnifiedConfigManager, data_manager: DataManager, db_path: str = "data/trainer_rules.db"):
        self.config_manager = config_manager
        self.data_manager = data_manager
        self.db_path = db_path
        self.logger = ProjectLogger.get_logger("LearningLoopsEngine")

        self.diary = DiaryEngine(data_manager)
        self.conn = sqlite3.connect(self.db_path, check_same_thread=False)
        self._initialize_database()

        self.rule_generator = ContextRuleGenerator(config_manager, data_manager)
        self.arena = get_trading_arena()

        self.logger.info(f"LearningLoopsEngine initialized with DB at {self.db_path}. Diary Engine connected.")

    @property
    def name(self) -> str:
        return "learning_loops"

    def update(self, data: Any) -> None:
        self.logger.info("Updating LearningLoopsEngine with new data.")
        if isinstance(data, dict) and data.get("trigger_review"):
            self.run_performance_review()
        else:
            self.run_hypothesis_generation(data.get("agent_id", "champion") if isinstance(data, dict) else "champion")

    def get_state(self) -> dict[str, Any]:
        cursor = self.conn.cursor()
        cursor.execute("SELECT COUNT(*) FROM rules")
        total_rules = cursor.fetchone()[0]

        leaderboard_data = self.arena.get_leaderboard()
        champion = leaderboard_data.get('leaderboard', [{}])[0].get('model_name', 'unknown')

        return {
            "total_rules_in_db": total_rules,
            "current_champion": champion,
            "db_path": self.db_path,
            "diary_status": self.diary.get_state()
        }

    def _initialize_database(self):
        with self.conn:
            self.conn.execute("""
                CREATE TABLE IF NOT EXISTS rules (
                    rule_id TEXT PRIMARY KEY,
                    description TEXT,
                    conditions TEXT NOT NULL,
                    action TEXT NOT NULL,
                    status TEXT NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)

    def run_hypothesis_generation(self, agent_id: str = "champion") -> list[TradingRule]:
        self.logger.info(f"Running hypothesis generation for agent '{agent_id}' using DiaryEngine vulnerabilities.")

        # 1. Get deep-analyzed context vulnerabilities from the Diary
        vulnerability_data = self.diary.get_context_vulnerability(agent_id)

        if vulnerability_data.get("status") == "No failure patterns detected" or not vulnerability_data.get("top_loss_fingerprints"):
            self.logger.info(f"No significant vulnerabilities found for agent '{agent_id}'. No new rules needed.")
            return []

        # 2. Use RuleGenerator to find statistical patterns in the context of losses (now more targeted)
        # Note: This part might need a refactor of ContextRuleGenerator to accept vulnerability data directly
        # For now, we simulate the old input from the vulnerability data for compatibility.
        top_loss_fingerprints = vulnerability_data.get('top_loss_fingerprints', [])
        if not top_loss_fingerprints:
             return []

        # This is a temporary compatibility layer.
        # Ideally, ContextRuleGenerator should be updated to use this rich data.
        simulated_losing_trades = self._simulate_trades_from_fingerprints(top_loss_fingerprints)

        generated_rules_data = self.rule_generator.generate_rules_from_context(simulated_losing_trades) # Assumes method exists

        new_rules = []
        for i, rule_data in enumerate(generated_rules_data):
            rule_id = f"RULE_{agent_id.upper()}_{datetime.now().strftime('%Y%m%d%H%M')}_{i}"

            new_rule = TradingRule(
                rule_id=rule_id,
                description=f"Diary-based rule: {rule_data['description']}",
                conditions=rule_data['conditions'],
                action=rule_data['action'],
                status="experimental"
            )

            self._save_rule(new_rule)
            new_rules.append(new_rule)
            self.logger.info(f"New hypothesis generated and saved from diary analysis: {rule_id}")

        return new_rules

    def _simulate_trades_from_fingerprints(self, fingerprints: list[dict[str, Any]]) -> pd.DataFrame:
        """Creates a mock DataFrame for the legacy Rule Generator."""
        records = []
        for fp_data in fingerprints:
            # Create one record per count to respect frequency
            for _ in range(fp_data.get('loss_count', 1)):
                records.append({
                    'context_fingerprint': fp_data.get('context_fingerprint')
                    # Add other columns if the rule generator needs them
                })
        return pd.DataFrame(records)

    def run_performance_review(self) -> dict[str, Any]:
        self.logger.info("Running system-wide performance review using DiaryEngine.")

        agent_ids = [model['model_name'] for model in self.arena.get_leaderboard().get('leaderboard', [])]
        if not agent_ids:
            self.logger.warning("No agents found in the Arena. Cannot perform review.")
            return {"action": "none", "reason": "no_agents_in_arena"}

        comparison_results = self.diary.compare_agents(agent_ids)

        recommendations = comparison_results.get("recommendations", [])
        if not recommendations:
            self.logger.info("Diary analysis complete. No promotion recommended. Current champion holds.")
            return {"action": "keep_champion", "details": "No agent showed significant outperformance."}

        top_recommendation = recommendations[0]
        if top_recommendation.get("type") == "PROMOTION":
            new_champion_id = top_recommendation['agent_id']

            self.logger.warning(f"PROMOTION ACTION: Promoting '{new_champion_id}' based on DiaryEngine analysis.")
            self.logger.warning(f"Reason: {top_recommendation.get('reason')}")

            self._update_rule_status_by_agent(new_champion_id, "validated")

            return {
                "action": "promote",
                "new_champion": new_champion_id,
                "analysis": top_recommendation
            }

        return {"action": "none", "reason": "No promotion recommendation found in analysis."}

    def _save_rule(self, rule: TradingRule):
        with self.conn:
            self.conn.execute("INSERT OR REPLACE INTO rules (rule_id, description, conditions, action, status) VALUES (?, ?, ?, ?, ?)", (
                rule.rule_id, rule.description, json.dumps(rule.conditions), rule.action, rule.status
            ))

    def _update_rule_status_by_agent(self, agent_id: str, new_status: str):
        with self.conn:
            self.conn.execute("UPDATE rules SET status = ? WHERE rule_id LIKE ?", (new_status, f"%{agent_id.upper()}%"))

    def get_rules_for_agent(self, status_list: list[str] | None=None) -> list[TradingRule]:
        if status_list is None:
            status_list = ["active", "validated"]
        placeholders = ', '.join(['?'] * len(status_list))
        query = f"SELECT * FROM rules WHERE status IN ({placeholders})"  # noqa: S608 — placeholders are ? params, not user input

        cursor = self.conn.cursor()
        cursor.execute(query, status_list)

        rules = []
        for row in cursor.fetchall():
            rules.append(TradingRule(
                rule_id=row[0],
                description=row[1],
                conditions=json.loads(row[2]),
                action=row[3],
                status=row[4]
            ))
        return rules

    def close(self):
        if self.conn:
            self.conn.close()
            self.logger.info("Trainer database connection closed.")
