#!/usr/bin/env python3
"""
Evolutionary Engine for A/B Testing and Hypothesis Validation

ARCHITECTURAL PURPOSE:
This is the "brain" of the meta-analyzer, or the "Trainer". Its job is to analyze the trading
results of the "Champion" and "Pretenders" to make the system better. It operates in two modes:

1.  HYPOTHESIS GENERATION: It analyzes the history of the "Champion's" errors (from the `ExperienceDiary`)
    and generates new "rules" (hypotheses for improvement) that could be tested.
    For example: "Avoid long positions when VIX > 30".

2.  PERFORMANCE EVALUATION: It periodically compares the financial results of the "Champion"
    and the "Pretenders" (which are testing new hypotheses). If a "Pretender" consistently
    shows better results, the "Trainer" signals this, proposing to
    "promote" its rules into the main strategy.

This module is an ORCHESTRATOR of the safe self-improvement process through A/B testing.
"""

import json
import sqlite3
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any


from src.analytics.arena.arena_battle import get_trading_arena
from src.config.unified_config_manager import UnifiedConfigManager
from src.core.logging.logger import ProjectLogger
from src.data.management.data_manager import DataManager
from src.devtools.rule_generator import ContextRuleGenerator
from src.meta_learning.base import BaseMetaComponent
from src.meta_learning.evolution.context_rule_synthesis import (
    MIN_EXCESS_LOSS_RATE,
    MIN_TRADES_FOR_RULE,
    synthesise_context_rules,
)
from src.meta_learning.memory.diary_engine import DecisionOutcome, DiaryEngine


class RuleStatus(Enum):
    """Formalized lifecycle states for trading rules."""
    EXPERIMENTAL = "experimental"  # Newly generated, not yet tested
    CANDIDATE = "candidate"        # Selected for testing in arena
    APPROVED = "approved"          # Passed arena testing, ready for promotion
    ACTIVE = "active"              # Currently in use by champion
    RETIRED = "retired"            # No longer used, kept for history


@dataclass
class TradingRule:
    """ Data contract for a single trading rule generated by the Trainer """
    rule_id: str
    description: str
    conditions: dict[str, Any]
    action: str
    status: RuleStatus = RuleStatus.EXPERIMENTAL
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    promoted_at: str | None = None
    retired_at: str | None = None

class LearningLoopsEngine(BaseMetaComponent):
    """
    The main class that implements the "Trainer" logic, integrating DataManager,
    RuleGenerator, and Arena for self-improving trading logic.
    """

    def __init__(self, config_manager: UnifiedConfigManager, data_manager: DataManager, db_path: str = "data/trainer_rules.db"):
        self.config_manager = config_manager
        self.data_manager = data_manager
        self.db_path = db_path
        self.logger = ProjectLogger.get_logger("LearningLoopsEngine")

        self.diary = DiaryEngine(data_manager)
        self.conn = sqlite3.connect(self.db_path, check_same_thread=False)
        self._initialize_database()

        # ContextRuleGenerator answers a different question from rule
        # synthesis (forward returns after an indicator crosses a threshold,
        # from price history) and is driven by its own run_analysis entry
        # point. Kept constructed because it is part of this engine's declared
        # surface; hypothesis generation no longer routes through it.
        self.rule_generator = ContextRuleGenerator(config_manager, data_manager)
        self.arena = get_trading_arena()

        self.logger.info(f"LearningLoopsEngine initialized with DB at {self.db_path}. Diary Engine connected.")

    @property
    def name(self) -> str:
        return "learning_loops"

    def update(self, data: Any) -> None:
        self.logger.info("Updating LearningLoopsEngine with new data.")
        if isinstance(data, dict) and data.get("trigger_review"):
            self.run_performance_review()
        else:
            self.run_hypothesis_generation(data.get("agent_id", "champion") if isinstance(data, dict) else "champion")

    def get_state(self) -> dict[str, Any]:
        cursor = self.conn.cursor()
        cursor.execute("SELECT COUNT(*) FROM rules")
        total_rules = cursor.fetchone()[0]

        leaderboard_data = self.arena.get_leaderboard()
        leaderboard = leaderboard_data.get('leaderboard') or [{}]
        champion = leaderboard[0].get('model_name', 'unknown')

        return {
            "total_rules_in_db": total_rules,
            "current_champion": champion,
            "db_path": self.db_path,
            "diary_status": self.diary.get_state()
        }

    def _initialize_database(self):
        with self.conn:
            self.conn.execute("""
                CREATE TABLE IF NOT EXISTS rules (
                    rule_id TEXT PRIMARY KEY,
                    description TEXT,
                    conditions TEXT NOT NULL,
                    action TEXT NOT NULL,
                    status TEXT NOT NULL,
                    created_at TEXT,
                    promoted_at TEXT,
                    retired_at TEXT
                )
            """)

    def run_hypothesis_generation(self, agent_id: str = "champion") -> list[TradingRule]:
        self.logger.info(f"Running hypothesis generation for agent '{agent_id}' using DiaryEngine vulnerabilities.")

        # 1. Get deep-analyzed context vulnerabilities from the Diary
        vulnerability_data = self.diary.get_context_vulnerability(agent_id)

        if vulnerability_data.get("status") == "No failure patterns detected" or not vulnerability_data.get("top_loss_fingerprints"):
            self.logger.info(f"No significant vulnerabilities found for agent '{agent_id}'. No new rules needed.")
            return []

        # 2. Use RuleGenerator to find statistical patterns in the context of losses (now more targeted)
        # Note: This part might need a refactor of ContextRuleGenerator to accept vulnerability data directly
        # For now, we simulate the old input from the vulnerability data for compatibility.
        top_loss_fingerprints = vulnerability_data.get('top_loss_fingerprints', [])
        if not top_loss_fingerprints:
             return []

        # This used to call ContextRuleGenerator.generate_rules_from_context,
        # a method that does not exist -- and could not simply be added,
        # because that class answers a different question (forward returns
        # after an indicator crosses a threshold, given price history) and
        # returns a different shape (indicator/condition/value/event_count/
        # effects_on_target, none of which is the description/conditions/
        # action read below).
        #
        # Rules now come from the diary's own decomposition. Each context
        # fingerprint is the concatenation of state_<FEATURE> columns at
        # -1/0/1, so a rule is a checkable statement about the market: "when
        # state_RSI_14 is +1, this agent loses 78% of the time (39 of 50),
        # against its own baseline of 52%". The excess over the agent's own
        # baseline is the part that says something about the STATE rather
        # than the agent.
        generated_rules_data = synthesise_context_rules(
            agent_id,
            vulnerability_data.get('component_loss_rates') or {},
            baseline_loss_rate=self.diary.agent_outcome_rate(
                agent_id, DecisionOutcome.UNPROFITABLE.value
            ),
        )
        if not generated_rules_data:
            # Said out loud rather than returned as a bare []: "no rule
            # cleared the evidence bar" and "the fingerprints could not be
            # decoded" look identical from the outside, and only the second
            # is a defect.
            self.logger.info(
                "No context rules for '%s': %d loss fingerprint(s) examined, "
                "components decoded=%s, none cleared the evidence thresholds "
                "(>= %d trades and >= %.0f%% above the agent's own loss rate).",
                agent_id, len(top_loss_fingerprints),
                vulnerability_data.get('components_decoded'),
                MIN_TRADES_FOR_RULE, MIN_EXCESS_LOSS_RATE * 100,
            )
            return []

        new_rules = []
        for i, rule_data in enumerate(generated_rules_data):
            rule_id = f"RULE_{agent_id.upper()}_{datetime.now().strftime('%Y%m%d%H%M')}_{i}"

            new_rule = TradingRule(
                rule_id=rule_id,
                description=f"Diary-based rule: {rule_data['description']}",
                conditions=rule_data['conditions'],
                action=rule_data['action'],
                status=RuleStatus.EXPERIMENTAL
            )

            self._save_rule(new_rule)
            new_rules.append(new_rule)
            self.logger.info(f"New hypothesis generated and saved from diary analysis: {rule_id}")

        return new_rules

    def run_performance_review(self) -> dict[str, Any]:
        self.logger.info("Running system-wide performance review using DiaryEngine.")

        agent_ids = [model['model_name'] for model in self.arena.get_leaderboard().get('leaderboard', [])]
        if not agent_ids:
            self.logger.warning("No agents found in the Arena. Cannot perform review.")
            return {"action": "none", "reason": "no_agents_in_arena"}

        comparison_results = self.diary.compare_agents(agent_ids)

        recommendations = comparison_results.get("recommendations", [])
        if not recommendations:
            self.logger.info("Diary analysis complete. No promotion recommended. Current champion holds.")
            return {"action": "keep_champion", "details": "No agent showed significant outperformance."}

        top_recommendation = recommendations[0]
        if top_recommendation.get("type") == "PROMOTION":
            new_champion_id = top_recommendation['agent_id']

            self.logger.warning(f"PROMOTION ACTION: Promoting '{new_champion_id}' based on DiaryEngine analysis.")
            self.logger.warning(f"Reason: {top_recommendation.get('reason')}")

            self._update_rule_status_by_agent(new_champion_id, "validated")

            return {
                "action": "promote",
                "new_champion": new_champion_id,
                "analysis": top_recommendation
            }

        return {"action": "none", "reason": "No promotion recommendation found in analysis."}

    def _save_rule(self, rule: TradingRule):
        with self.conn:
            self.conn.execute(
                "INSERT OR REPLACE INTO rules (rule_id, description, conditions, action, status, created_at, promoted_at, retired_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                (rule.rule_id, rule.description, json.dumps(rule.conditions), rule.action, rule.status.value, rule.created_at, rule.promoted_at, rule.retired_at)
            )

    def promote_rule(self, rule_id: str, new_status: RuleStatus) -> bool:
        """
        Explicit promotion gate for rule lifecycle transitions.
        
        Args:
            rule_id: The rule to promote
            new_status: The target status (must follow lifecycle order)
            
        Returns:
            bool: True if promotion successful, False otherwise
        """
        # Define valid lifecycle transitions
        valid_transitions = {
            RuleStatus.EXPERIMENTAL: [RuleStatus.CANDIDATE, RuleStatus.RETIRED],
            RuleStatus.CANDIDATE: [RuleStatus.APPROVED, RuleStatus.RETIRED],
            RuleStatus.APPROVED: [RuleStatus.ACTIVE, RuleStatus.RETIRED],
            RuleStatus.ACTIVE: [RuleStatus.RETIRED],
            RuleStatus.RETIRED: []
        }

        # Get current status
        cursor = self.conn.cursor()
        cursor.execute("SELECT status FROM rules WHERE rule_id = ?", (rule_id,))
        row = cursor.fetchone()
        if not row:
            self.logger.error(f"Rule {rule_id} not found")
            return False

        current_status = RuleStatus(row[0])

        # Validate transition
        if new_status not in valid_transitions[current_status]:
            self.logger.error(f"Invalid transition from {current_status.value} to {new_status.value} for rule {rule_id}")
            return False

        # Update status with timestamp
        timestamp = datetime.now().isoformat()
        timestamp_field = "promoted_at" if new_status in [RuleStatus.APPROVED, RuleStatus.ACTIVE] else "retired_at"

        with self.conn:
            self.conn.execute(
                f"UPDATE rules SET status = ?, {timestamp_field} = ? WHERE rule_id = ?",
                (new_status.value, timestamp, rule_id)
            )

        self.logger.info(f"Rule {rule_id} promoted from {current_status.value} to {new_status.value}")
        return True

    def _update_rule_status_by_agent(self, agent_id: str, new_status: str):
        # Convert string status to RuleStatus enum
        try:
            status_enum = RuleStatus(new_status)
        except ValueError:
            self.logger.error(f"Invalid status: {new_status}")
            return

        # Get all rules for this agent
        cursor = self.conn.cursor()
        cursor.execute("SELECT rule_id FROM rules WHERE rule_id LIKE ?", (f"%{agent_id.upper()}%",))
        rule_ids = [row[0] for row in cursor.fetchall()]

        # Promote each rule through the explicit promotion gate
        for rule_id in rule_ids:
            self.promote_rule(rule_id, status_enum)

    def get_rules_for_agent(self, status_list: list[str] | None=None) -> list[TradingRule]:
        if status_list is None:
            status_list = [RuleStatus.ACTIVE.value, RuleStatus.APPROVED.value]
        placeholders = ', '.join(['?'] * len(status_list))
        query = f"SELECT * FROM rules WHERE status IN ({placeholders})"  # noqa: S608 — placeholders are ? params, not user input

        cursor = self.conn.cursor()
        cursor.execute(query, status_list)

        rules = []
        for row in cursor.fetchall():
            rules.append(TradingRule(
                rule_id=row[0],
                description=row[1],
                conditions=json.loads(row[2]),
                action=row[3],
                status=RuleStatus(row[4]),
                created_at=row[5],
                promoted_at=row[6],
                retired_at=row[7]
            ))
        return rules

    def close(self):
        if self.conn:
            self.conn.close()
            self.logger.info("Trainer database connection closed.")
