sonar.projectKey=OleksanderSS_trading_project
sonar.organization=oleksanderss
sonar.sources=src
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.ipynb_checkpoints/**,**/*.ipynb,**/.gemini/**,**/venv/**,**/.venv/**,src/colab/**,src/devtools/**,src/trained_models/**
