# Comprehensive Vulture Whitelist
# This whitelist captures patterns for complex, dynamic, and framework-based code
# commonly used in this trading system.

# Dataclass/Pydantic/Schema attributes
Config
arbitrary_types_allowed
model_config
last_updated

# Enums/Constants
INCONCLUSIVE
BUY
SELL
HOLD
STOP
WEAK
MODERATE
STRONG
MINUTE_1
MINUTE_5
MINUTE_15
MINUTE_30
HOUR_1
HOUR_4
DAY_1
WEEK_1
CORPORATE_NEWS
WEATHER
SOCIAL_SENTIMENT
SCALPING
DAY_TRADING
SWING_TRADING
POSITION_TRADING
INVESTING
TECH
FINANCE
HEALTHCARE
ENERGY
COMMODITIES
FUTURE_INFORMATION
INFORMATION_LEAKAGE
SELECTION_BIAS
SURVIVORSHIP_BIAS
MULTIPLE_COMPARISON
TESTING
ACKNOWLEDGED
GAUGE
COUNTER
HISTOGRAM
SUMMARY
CONSERVATIVE
BALANCED
AGGRESSIVE

# Patterns for dynamic/library-like components
analyze
conduct_battle
register_model
__init__
predict
forecast
evaluate
get_status
collect_data
harmonize_batch
deduplicate

# Registry & Factory Patterns (prevent false positives)
get_analyzer
create_argument_parser
get_performance_tracker
get_trading_arena
get_model_pool
get_persistent_pool
get_feature_selection_cache
get_prediction_cache
get_data_versioning
create_validation_middleware
get_simulation_engine
get_session_client
get_by_version
get_leaderboard_categories
get_model_stats
get_model_performance_history
save_performance_data
load_performance_data
save_all_scalers
load_scalers

# Commonly used utilities that are 'libraries' to the app
save_json
load_json
save_yaml
load_dataframe
cleanup_old_files
is_healthy
log_structured
log_cache_miss
log_model_loaded
get_metrics_summary
sanitize_timestamps
format_percentage
safe_divide
clamp_value
ensure_dataframe
ensure_array

# Specific dynamic call paths
_calculate_dynamic
_find_dynamic
_can_calculate_dynamic
_get_dynamic_data
_handle_missing_dynamic
_create_dynamic
_process_dynamic
_run_dynamic
_update_dynamic
_save_dynamic
_load_dynamic
_validate_dynamic
_log_dynamic
_get_or_compute_dynamic
_generate_dynamic
_determine_dynamic
_get_instance_dynamic
_calculate_metrics

# Infrastructure variables
_secrets_cache
_performance_tracker
_trading_arena
_model_pool
_persistent_pool
_data_versioning
_feature_selection_cache
_prediction_cache
_last_known_scores
last_checkpoint
drift_cooldowns
stability_cache
network_timeout
mae_threshold
outlier_threshold
quality_history
refresh_interval
history_days
active
emergency_closure_active
prediction_config
critical_signal_detector
market_context_analyzer
signal_analytics
significance_detector
causal_finder
enhanced_consensus
simulation_engine
adaptive_position_sizer
risk_parity_allocator
volatility_calculator
drawdown_calculator
risk_reward_calculator
market_phase_analyzer
macro_context_analyzer
confidence_calibrator
last_performance_update
data_collector
model_registry
training_history
target_generator
unified_manager
api_limiter
collector_limiter
processor_limiter
combined_path
