"""
Orchestrates the entire trading process for Stage 6.

This module connects the different components of the trading pipeline:
- Gets signals from the Consensus Engine.
- Gets trade orders from the Portfolio Manager.
- Executes orders via the Trader.
- Updates the state of the Virtual Portfolio.
"""

from typing import List, Dict
from src.core.logging.logger import ProjectLogger
from src.trading.consensus_engine import ConsensusEngine
from src.trading.portfolio_manager import PortfolioManager
from src.trading.virtual_portfolio import VirtualPortfolio
from src.trading.trader import Trader, TradeOrder
from src.trading.post_inference_filter import PostInferenceFilter

class TradingOrchestrator:
    """
    Manages the flow of information from signal generation to execution.
    """

    def __init__(self, 
                 consensus_engine: ConsensusEngine,
                 portfolio_manager: PortfolioManager,
                 virtual_portfolio: VirtualPortfolio,
                 trader: Trader,
                 post_inference_filter: Optional[PostInferenceFilter] = None):
        """
        Initializes the orchestrator with all necessary trading components.
        """
        self.logger = ProjectLogger.get_logger(self.__class__.__name__)
        self.consensus_engine = consensus_engine
        self.portfolio_manager = portfolio_manager
        self.portfolio = virtual_portfolio
        self.trader = trader
        self.filter = post_inference_filter
        self.logger.info("TradingOrchestrator initialized and ready.")

    def process_signals(self, 
                        raw_predictions: List[Dict[str, any]], 
                        current_prices: Dict[str, float]):
        """
        The main entry point to process a batch of new model predictions.
        
        Args:
            raw_predictions: A list of prediction dicts from Stage 5.
            current_prices: A dict mapping tickers to their current market prices.
        """
        self.logger.info(f"Starting new trading cycle with {len(raw_predictions)} raw predictions.")

        # 1. (Optional) Pre-filter raw predictions
        if self.filter:
            # Assuming predictions are in a DataFrame-compatible format
            import pandas as pd
            predictions_df = pd.DataFrame(raw_predictions)
            filtered_df = self.filter.apply(predictions_df)
            predictions_to_process = filtered_df.to_dict('records')
        else:
            predictions_to_process = raw_predictions

        # 2. Generate consensus from (filtered) predictions
        # This needs to be adapted based on ConsensusEngine's final input signature
        consensus_signals = []
        for prediction in predictions_to_process:
             # This is a placeholder. The actual call will depend on the 
             # exact inputs required by consensus_engine.generate_consensus
             # For now, we assume it takes a prediction dictionary.
             report = self.consensus_engine.generate_consensus(prediction, prediction) # Dummy context
             if report.final_signal != 'HOLD':
                signal_data = {
                    'ticker': prediction['ticker'],
                    'final_signal': report.final_signal,
                    'confidence': report.confidence,
                    'report': report # Pass the full report for richer logging/decisions
                }
                consensus_signals.append(signal_data)
        
        if not consensus_signals:
            self.logger.info("No actionable signals after consensus. Cycle finished.")
            return

        self.logger.info(f"{len(consensus_signals)} actionable signals generated by Consensus Engine.")

        # 3. Check for risk-based exits (SL/TP) FIRST
        exit_orders = self.portfolio_manager.check_risk_exits(current_prices)
        if exit_orders:
            self.logger.info(f"Generated {len(exit_orders)} exit orders due to SL/TP triggers.")
            self._execute_orders(exit_orders)

        # 4. Generate new entry/exit orders from consensus signals
        trade_orders = self.portfolio_manager.generate_orders_from_signals(consensus_signals, current_prices)

        if not trade_orders:
            self.logger.info("No trade orders generated by Portfolio Manager. Cycle finished.")
            return

        self.logger.info(f"Generated {len(trade_orders)} new trade orders.")

        # 5. Execute all generated orders
        self._execute_orders(trade_orders)

        # 6. Update portfolio performance metrics and save state
        self.portfolio.update_performance(current_prices)
        self.logger.info("Portfolio performance updated and state saved.")

    def _execute_orders(self, orders: List[TradeOrder]):
        """
        Sends orders to the trader and updates the portfolio upon success.
        """
        for order in orders:
            success = self.trader.execute_order(order)
            if success:
                self.logger.info(f"Successfully executed order: {order}. Updating portfolio state.")
                # The trader only simulates. Now we tell the portfolio to update its state.
                if order.action == 'BUY':
                    self.portfolio.buy_stock(order.ticker, order.quantity, order.price, reason=order.reason)
                elif order.action == 'SELL':
                    self.portfolio.sell_stock(order.ticker, order.quantity, order.price, reason=order.reason)
            else:
                self.logger.error(f"Failed to execute order: {order}. Portfolio not updated.")

