#!/usr/bin/env python3
"""
Audit gate for findings emitted by deep_static_audit.py.

Purpose:
- compare current findings with a committed baseline;
- apply explicit suppressions with reasons/expiry;
- fail CI only on new or unsuppressed findings above configured severity;
- keep review workflow deterministic/offline.

Typical workflow:
  # 1) generate current findings
  python audit_tools/deep_static_audit.py --root src --out audit_reports --format all

  # 2) create a baseline once after manual triage
  python audit_tools/audit_gate.py baseline \
      --findings audit_reports/findings.json \
      --baseline audit_reports/audit_baseline.json

  # 3) CI/check mode on later runs
  python audit_tools/audit_gate.py check \
      --findings audit_reports/findings.json \
      --baseline audit_reports/audit_baseline.json \
      --suppressions audit_tools/audit_suppressions.yaml \
      --fail-on P0,P1 \
      --out audit_reports/gate_report.md

Suppression YAML format:
  suppressions:
    - fingerprint: "abc123..."
      reason: "False positive: demo fixture, not production path"
      owner: "ml-platform"
      expires: "2026-12-31"
    - rule_id: "FEATURE_WITHOUT_LOCAL_LINEAGE_HINT"
      file: "features/legacy_enricher.py"
      reason: "Legacy module scheduled for removal"
      expires: "2026-09-30"

Exit codes:
  0 - pass
  1 - gate failed due to new/unsuppressed findings
  2 - config/input error
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

SEVERITY_ORDER = {"P0": 0, "P1": 1, "P2": 2, "P3": 3, "INFO": 4}


def load_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise SystemExit(f"Missing file: {path}")
    except json.JSONDecodeError as e:
        raise SystemExit(f"Invalid JSON {path}: {e}")


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True), encoding="utf-8")


def parse_fail_on(value: str) -> set[str]:
    severities = {s.strip().upper() for s in value.split(",") if s.strip()}
    invalid = severities - set(SEVERITY_ORDER)
    if invalid:
        raise SystemExit(f"Unknown severities in --fail-on: {sorted(invalid)}")
    return severities


def minimal_finding(f: dict[str, Any]) -> dict[str, Any]:
    keys = [
        "fingerprint", "severity", "category", "rule_id", "file", "line",
        "problem", "confidence",
    ]
    return {k: f.get(k) for k in keys if k in f}


def create_baseline(findings_path: Path, baseline_path: Path) -> int:
    findings = load_json(findings_path)
    if not isinstance(findings, list):
        raise SystemExit("findings JSON must be a list")

    baseline = {
        "version": 1,
        "created_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "source_findings": str(findings_path),
        "count": len(findings),
        "by_severity": dict(Counter(f.get("severity", "UNKNOWN") for f in findings)),
        "findings": [minimal_finding(f) for f in findings],
    }
    write_json(baseline_path, baseline)
    print(f"Baseline written: {baseline_path}")
    print(f"Baseline findings: {len(findings)}")
    return 0


def _simple_yaml_load(path: Path) -> dict[str, Any]:
    """Tiny YAML subset parser to avoid dependency on PyYAML.

    Supports exactly the suppression structure generated by this tool:
      suppressions:
        - fingerprint: "..."
          reason: "..."
          expires: "YYYY-MM-DD"
    Also supports rule_id/file/category/severity/owner.
    """
    if not path.exists():
        return {"suppressions": []}

    text = path.read_text(encoding="utf-8")
    items: list[dict[str, str]] = []
    cur: dict[str, str] | None = None
    in_suppressions = False

    for raw_line in text.splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped == "suppressions:":
            in_suppressions = True
            continue
        if not in_suppressions:
            continue
        if stripped.startswith("- "):
            if cur:
                items.append(cur)
            cur = {}
            stripped = stripped[2:].strip()
            if stripped:
                if ":" not in stripped:
                    raise SystemExit(f"Invalid suppression line in {path}: {raw_line}")
                k, v = stripped.split(":", 1)
                cur[k.strip()] = _unquote(v.strip())
            continue
        if cur is not None and ":" in stripped:
            k, v = stripped.split(":", 1)
            cur[k.strip()] = _unquote(v.strip())
            continue
        raise SystemExit(f"Unsupported YAML syntax in {path}: {raw_line}")

    if cur:
        items.append(cur)
    return {"suppressions": items}


def _unquote(value: str) -> str:
    value = value.strip()
    if value in {"", "null", "None", "~"}:
        return ""
    if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
        return value[1:-1]
    return value


def load_suppressions(path: Path | None) -> list[dict[str, str]]:
    if path is None:
        return []
    data = _simple_yaml_load(path)
    suppressions = data.get("suppressions", [])
    if not isinstance(suppressions, list):
        raise SystemExit("suppressions must be a list")

    today = dt.date.today()
    active: list[dict[str, str]] = []
    expired: list[dict[str, str]] = []
    for s in suppressions:
        if not isinstance(s, dict):
            raise SystemExit("each suppression must be a mapping")
        reason = str(s.get("reason", "")).strip()
        if not reason:
            raise SystemExit(f"suppression missing reason: {s}")
        expires = str(s.get("expires", "")).strip()
        if expires:
            try:
                exp_date = dt.date.fromisoformat(expires)
            except ValueError:
                raise SystemExit(f"suppression has invalid expires date {expires!r}: {s}")
            if exp_date < today:
                expired.append(s)
                continue
        active.append({str(k): str(v) for k, v in s.items()})

    if expired:
        print(f"Warning: ignored {len(expired)} expired suppressions", file=sys.stderr)
    return active


def matches_suppression(f: dict[str, Any], s: dict[str, str]) -> bool:
    # Fingerprint is exact and strongest.
    if s.get("fingerprint"):
        return str(f.get("fingerprint")) == s["fingerprint"]

    # Otherwise all specified fields must match.
    match_fields = ["rule_id", "file", "category", "severity"]
    specified = [k for k in match_fields if s.get(k)]
    if not specified:
        return False
    return all(str(f.get(k, "")) == s[k] for k in specified)


def classify_findings(findings: list[dict[str, Any]], baseline: dict[str, Any], suppressions: list[dict[str, str]]) -> dict[str, list[dict[str, Any]]]:
    baseline_fps = {str(f.get("fingerprint")) for f in baseline.get("findings", []) if f.get("fingerprint")}
    result: dict[str, list[dict[str, Any]]] = defaultdict(list)

    for f in findings:
        suppressed_by = next((s for s in suppressions if matches_suppression(f, s)), None)
        enriched = dict(f)
        if suppressed_by:
            enriched["suppressed_by"] = {k: suppressed_by.get(k, "") for k in ["fingerprint", "rule_id", "file", "reason", "owner", "expires"] if suppressed_by.get(k, "")}
            result["suppressed"].append(enriched)
        elif str(f.get("fingerprint")) in baseline_fps:
            result["existing"].append(enriched)
        else:
            result["new"].append(enriched)
    return result


def render_gate_report(classified: dict[str, list[dict[str, Any]]], fail_on: set[str], failed: list[dict[str, Any]]) -> str:
    lines: list[str] = []
    lines.append("# Audit Gate Report\n")
    lines.append(f"Generated at: {dt.datetime.now(dt.timezone.utc).isoformat()}\n")
    lines.append("## Summary\n")
    for group in ["new", "existing", "suppressed"]:
        items = classified.get(group, [])
        counts = Counter(str(f.get("severity", "UNKNOWN")) for f in items)
        suffix = ", ".join(f"{sev}: {counts[sev]}" for sev in sorted(counts, key=lambda s: SEVERITY_ORDER.get(s, 99)))
        lines.append(f"- {group}: {len(items)}" + (f" ({suffix})" if suffix else ""))
    lines.append(f"- fail_on: {', '.join(sorted(fail_on, key=lambda s: SEVERITY_ORDER.get(s, 99)))}")
    lines.append(f"- gate_status: {'FAIL' if failed else 'PASS'}")

    if failed:
        lines.append("\n## Failing new findings\n")
        for f in sorted(failed, key=lambda x: (SEVERITY_ORDER.get(str(x.get("severity")), 99), str(x.get("file")), int(x.get("line") or 0))):
            lines.append(f"### {f.get('severity')} {f.get('category')} / {f.get('rule_id')} — `{f.get('file')}:{f.get('line')}`")
            lines.append(f"**Problem:** {f.get('problem', '')}")
            lines.append(f"**Fingerprint:** `{f.get('fingerprint', '')}`")
            snippet = str(f.get("snippet", ""))[:900]
            if snippet:
                lines.append("```python")
                lines.append(snippet)
                lines.append("```")
            lines.append("")

    if classified.get("suppressed"):
        lines.append("\n## Suppressed findings\n")
        for f in classified["suppressed"][:100]:
            s = f.get("suppressed_by", {})
            lines.append(f"- `{f.get('fingerprint')}` {f.get('severity')} {f.get('rule_id')} `{f.get('file')}:{f.get('line')}` — {s.get('reason', '')}")
        if len(classified["suppressed"]) > 100:
            lines.append(f"- ... {len(classified['suppressed']) - 100} more")

    return "\n".join(lines) + "\n"


def check_gate(findings_path: Path, baseline_path: Path, suppressions_path: Path | None, fail_on: set[str], out_path: Path | None) -> int:
    findings = load_json(findings_path)
    baseline = load_json(baseline_path)
    if not isinstance(findings, list):
        raise SystemExit("findings JSON must be a list")
    if not isinstance(baseline, dict):
        raise SystemExit("baseline JSON must be an object")

    suppressions = load_suppressions(suppressions_path)
    classified = classify_findings(findings, baseline, suppressions)
    failed = [f for f in classified["new"] if str(f.get("severity")) in fail_on]

    report = render_gate_report(classified, fail_on, failed)
    if out_path:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(report, encoding="utf-8")
    else:
        print(report)

    print(f"New findings: {len(classified['new'])}")
    print(f"Existing findings: {len(classified['existing'])}")
    print(f"Suppressed findings: {len(classified['suppressed'])}")
    print(f"Gate: {'FAIL' if failed else 'PASS'}")
    return 1 if failed else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Baseline/suppression CI gate for deep static audit findings")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_base = sub.add_parser("baseline", help="Create/update baseline from current findings")
    p_base.add_argument("--findings", required=True)
    p_base.add_argument("--baseline", required=True)

    p_check = sub.add_parser("check", help="Compare current findings against baseline and suppressions")
    p_check.add_argument("--findings", required=True)
    p_check.add_argument("--baseline", required=True)
    p_check.add_argument("--suppressions")
    p_check.add_argument("--fail-on", default="P0,P1")
    p_check.add_argument("--out")

    args = parser.parse_args(argv)
    if args.cmd == "baseline":
        return create_baseline(Path(args.findings), Path(args.baseline))
    if args.cmd == "check":
        return check_gate(
            findings_path=Path(args.findings),
            baseline_path=Path(args.baseline),
            suppressions_path=Path(args.suppressions) if args.suppressions else None,
            fail_on=parse_fail_on(args.fail_on),
            out_path=Path(args.out) if args.out else None,
        )
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
